# Generated by Django 5.2.6 on 2026-02-07 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0002_doctor_avg_minutes_per_patient_doctor_current_token'),
        ('appointments', '0004_appointment_checked_in_appointment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['date', 'token_number']},
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'date', 'token_number')},
        ),
    ]
