# Generated by Django 5.2.6 on 2026-02-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='fullname',
            field=models.CharField(max_length=100),
        ),
    ]
