# Generated by Django 5.2.6 on 2026-02-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0002_alter_patients_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
