# Generated by Django 5.2.6 on 2026-02-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('specialization', models.CharField(max_length=100)),
                ('experience', models.IntegerField(help_text='Years of experience')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
