# Generated by Django 5.2.6 on 2026-02-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='avg_minutes_per_patient',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='doctor',
            name='current_token',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
